"""Purpose: Store canonical-to-container tag mappings and preserved field policies."""

PRESERVE_RAW_FIELDS = {
    "rating",
    "comment",
    "grouping",
    "replaygain_track_gain",
    "replaygain_album_gain",
    "bpm",
    "initial_key",
    "mood",
}

VORBIS_FIELD_MAP = {
    "title": "TITLE",
    "artist": "ARTIST",
    "album": "ALBUM",
    "album_artist": "ALBUMARTIST",
    "track_number": "TRACKNUMBER",
    "track_total": "TRACKTOTAL",
    "disc_number": "DISCNUMBER",
    "disc_total": "DISCTOTAL",
    "release_date": "DATE",
    "original_date": "ORIGINALDATE",
    "genre": "GENRE",
    "subgenre": "STYLE",
    "composer": "COMPOSER",
    "comment": "COMMENT",
    "grouping": "GROUPING",
    "label": "LABEL",
    "copyright": "COPYRIGHT",
    "isrc": "ISRC",
    "musicbrainz_recording_id": "MUSICBRAINZ_TRACKID",
    "musicbrainz_release_id": "MUSICBRAINZ_ALBUMID",
    "musicbrainz_release_group_id": "MUSICBRAINZ_RELEASEGROUPID",
    "musicbrainz_artist_id": "MUSICBRAINZ_ARTISTID",
    "discogs_release_id": "DISCOGS_RELEASE_ID",
    "barcode": "BARCODE",
    "catalog_number": "CATALOGNUMBER",
    "bpm": "BPM",
    "key": "INITIALKEY",
    "mood": "MOOD",
    "energy": "ENERGY",
    "vocal_presence": "VOCALPRESENCE",
    "instruments": "INSTRUMENTS",
    "language": "LANGUAGE",
}

MP4_FIELD_MAP = {
    "title": "\xa9nam",
    "artist": "\xa9ART",
    "album": "\xa9alb",
    "album_artist": "aART",
    "release_date": "\xa9day",
    "genre": "\xa9gen",
    "composer": "\xa9wrt",
    "comment": "\xa9cmt",
    "grouping": "\xa9grp",
    "copyright": "cprt",
    "bpm": "tmpo",
}

ID3_TEXT_FRAME_MAP = {
    "title": "TIT2",
    "artist": "TPE1",
    "album": "TALB",
    "album_artist": "TPE2",
    "release_date": "TDRC",
    "original_date": "TDOR",
    "genre": "TCON",
    "composer": "TCOM",
    "comment": "COMM",
    "grouping": "TIT1",
    "copyright": "TCOP",
    "isrc": "TSRC",
    "barcode": "TXXX:BARCODE",
    "musicbrainz_recording_id": "TXXX:MusicBrainz Track Id",
    "musicbrainz_release_id": "TXXX:MusicBrainz Album Id",
    "musicbrainz_release_group_id": "TXXX:MusicBrainz Release Group Id",
    "musicbrainz_artist_id": "TXXX:MusicBrainz Artist Id",
    "discogs_release_id": "TXXX:Discogs Release Id",
    "catalog_number": "TXXX:Catalog Number",
    "bpm": "TBPM",
    "key": "TKEY",
    "mood": "TMOO",
}
